# Generated by Django 6.0.3 on 2026-04-02 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('use_case', models.CharField(choices=[('inventory', 'Inventario / Productos'), ('students', 'Alumnos'), ('clients', 'Clientes'), ('generic', 'General')], default='inventory', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_databases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'Alta'), ('urgent', 'Urgente')], default='normal', max_length=12)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_records', to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='app.appdatabase')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('key', models.SlugField(max_length=80)),
                ('field_type', models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('currency', 'Moneda'), ('boolean', 'Si / No'), ('date', 'Fecha')], max_length=12)),
                ('help_text', models.CharField(blank=True, max_length=180)),
                ('required', models.BooleanField(default=False)),
                ('show_in_table', models.BooleanField(default=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.appdatabase')),
            ],
            options={
                'ordering': ['position', 'id'],
                'unique_together': {('database', 'key')},
            },
        ),
        migrations.CreateModel(
            name='DatabaseMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('editor', 'Editor')], default='editor', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='app.appdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['database', 'user__username'],
                'unique_together': {('database', 'user')},
            },
        ),
    ]
