# Generated by Django 6.0.3 on 2026-04-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='options_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customfield',
            name='relation_database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_relation_fields', to='app.appdatabase'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('number', 'Numero'), ('currency', 'Moneda'), ('boolean', 'Si / No'), ('date', 'Fecha'), ('email', 'Email'), ('phone', 'Telefono'), ('select', 'Seleccion'), ('relation', 'Relacion con otra base')], max_length=12),
        ),
    ]
