# Generated by Django 6.0.3 on 2026-04-04 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_databaseactivity_payload'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('field_key', models.CharField(default='__created_at__', max_length=80)),
                ('chart_type', models.CharField(choices=[('auto', 'Automatico'), ('bars', 'Barras'), ('donut', 'Dona'), ('table', 'Tabla'), ('metrics', 'Metricas')], default='auto', max_length=16)),
                ('query', models.CharField(blank=True, max_length=120)),
                ('priority', models.CharField(blank=True, max_length=12)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('database', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_statistics', to='app.appdatabase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_statistics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('database', 'user', 'name')},
            },
        ),
    ]
