# Generated by Django 6.0.3 on 2026-04-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_record_archived_at_record_archived_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Texto'), ('description', 'Descripcion'), ('number', 'Numero'), ('currency', 'Moneda'), ('boolean', 'Si / No'), ('date', 'Fecha'), ('email', 'Email'), ('phone', 'Telefono'), ('select', 'Seleccion'), ('relation', 'Relacion con otra base')], max_length=12),
        ),
    ]
